DROP TABLE IF EXISTS login;

CREATE TABLE login
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email    TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    salt     TEXT NOT NULL UNIQUE,
    dirname  TEXT NOT NULL UNIQUE
);